<style>
    #forumthread{
       list-style: none;
       
    }
    #forumthread li{
        width:95%;
        margin: auto;
        font-size: 1.8em;
        padding:8px;
        margin-bottom: 10px;
    }
    
    #title{
        font-size: 4em;
    }
</style>
<section class="row" style="margin-left:50px;"><br><br><br><br>
<h2 style="color:grey"><b>Terms and Conditions</b></h4>
<div style="background : #000;border : solid 2px #fff; color : #ffffff; padding : 4px; width : 1000px; height : 500px; overflow : auto; ">

<h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of <a href="http://www.indianphotographyedition.com">www.indianphotographyedition.com</a> website.
        

    <br><br>

The domain name <a href="http://www.indianphotographyedition.com"><b>www.indianphotographyedition.com</b></a> (hereinafter referred to as "Website") is owned by Indian photography edition Private Limited a company incorporated under the Companies Act, 1956.
<br><br>
Your use of the Website and services and tools are governed by the following terms and conditions <b>(“Terms of Use”)</b> as applicable to the Website including the applicable policies which are incorporated herein by way of reference. If you transact on the Website, You shall be subject to the policies that are applicable to the Website for such transaction. By mere use of the Website, You shall be contracting with <b>Indianphotographyedition</b> Internet Private Limited and these terms and conditions including the policies constitute Your binding obligations, with <b>Indianphotographyedition</b>
For the purpose of these Terms of Use, wherever the context so requires "You" or “User” shall mean any natural or legal person who has agreed to Terms of use by proceeding to surf the website opting for “I Accept” tab  on the Home Page of the Website and/or by providing Registration Data while registering on the Website as Registered User using the computer systems. <b>Indianphotographyedition</b>  allows the User to surf the Website without registering on the Website. The term “We”, “Us”, “Our” shall mean <b>Indianphotographyedition</b> Internet Private Limited.
When You use any of the services provided by Us through the Website, including but not limited to, (e.g. Product Reviews, Seller Reviews, Owners copyrights), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Website following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.
<br><br>
ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Indianphotographyedition Policies (including but not limited to Privacy Policy available on <a href="http://indianphotographyedition.com/index.php/welcome/privacy">http://indianphotographyedition.com/index.php/welcome/privacy</a>) as amended from time to time.
</font></h3>
<h4 style="color:grey;">Membership Eligibility</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
Use of the Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Website. If you are a minor i.e. under the age of 18 years, you shall not register as a User of the Indianphotographyedition website and shall not transact on or use the website. As a minor if you wish to use or transact on website, such use or transaction may be made by your legal guardian or parents on the Website. Indianphotographyedition reserves the right to terminate your membership and / or refuse to provide you with access to the Website if it is brought to Indianphotographyedition’s notice or if it is discovered that you are under the age of 18 years.

        </font></h3>

<br><br>

<h4 style=“color:grey”>Your Account and Registration Obligations</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
If You use the Website, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Website and refuse to provide You with access to the Website.

        </font></h3>

<br><br>
<h4 style=“color:grey”>Communications</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
When You use the Website or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise.

        </font></h3>

<br><br>
<h4 style=“color:grey”>Platform for Posting Professional Photographs and Products Related to Photography</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
The Website is a platform for user who are interested in professional / Exclusive / Patented photography to upload their work and also find products which are suitable for the said purpose. Indianphotographyedition is not and cannot be a party to or control in any manner any transaction between the Website’s Users.
Henceforward:
1. All commercial/contractual terms are offered by and agreed to between Buyers and Sellers alone. The commercial/contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period and mode of delivery, warranties related to products and services and after sales services related to products and services. Indianphotographyedition does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers.
2. Indianphotographyedition does not make any representation or Warranty as to specifics (such as quality, value, salability, etc) of the products or services proposed to be sold or offered to be sold or purchased on the Website. Indianphotographyedition does not implicitly or explicitly support or endorse the sale or purchase of any products or services on the Website. Indianphotographyedition accepts no liability for any errors or omissions, whether on behalf of itself or third parties.
3. Indianphotographyedition is not responsible for any non-performance or breach of any contract entered into between Buyers and Sellers. Indianphotographyedition cannot and does not guarantee that the concerned Buyers and/or Sellers will perform any transaction concluded on the Website. Indianphotographyedition shall not and is not required to mediate or resolve any dispute or disagreement between Buyers and Sellers.
4. Indianphotographyedition does not make any representation or warranty as to the item-specifics (such as legal title, creditworthiness, identity, etc) of any of its Users. You are advised to independently verify the bona fides of any particular User that You choose to deal with on the Website and use Your best judgment in that behalf.
5. Indianphotographyedition does not at any point of time during any transaction between Buyer and Seller on the Website come into or take possession of any of the products or services offered by Seller nor does it at any point gain title to or have any rights or claims over the products or services offered by Seller to Buyer.
 6. At no time shall Indianphotographyedition hold any right, title or interest over the products nor shall Indianphotographyedition have any obligations or liabilities in respect of such contract entered into between Buyers and Sellers. Indianphotographyedition is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back ordered.
At no time shall Indianphotographyedition hold any right, title or interest over the products or photographs uploaded for display nor shall Indianphotographyedition have any obligations or liabilities in respect of such contract.
Indianphotographyedition is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are unavailable or back ordered.
8. You shall independently agree upon the manner and terms and conditions of delivery, payment, insurance etc. with the seller(s) that You transact with.
Disclaimer: Pricing on any product(s) as is reflected on the Website may due to some technical issue, typographical error or product information published by seller may be incorrectly reflected and in such an event seller may cancel such your order(s). 
9. You release and indemnify Indianphotographyedition and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the Users of the Website and specifically waive any claims that you may have in this behalf under any applicable law. Notwithstanding its reasonable efforts in that behalf, Indianphotographyedition cannot take responsibility or control the information provided by other Users which is made available on the Website. You may find other User's information / images / products to be offensive, harmful, inconsistent, inaccurate, or deceptive. Please use caution and practice safe trading when using the Website.
Please note that there could be risks in dealing with underage persons or people acting under false pretence.

        </font></h3>

<br><br>
<h4 style=“color:grey”>Charges</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
Membership on the Website is free for Members .Indianphotographyedition does not charge any fee for browsing and buying on the Website. Indianphotographyedition reserves the right to change its Fee Policy from time to time. In particular, Indianphotographyedition may at its sole discretion introduce new services and modify some or all of the existing services offered on the Website. In such an event Indianphotographyedition reserves the right to introduce fees for the new services offered or amend/introduce fees for existing services, as the case may be. Changes to the Fee Policy shall be posted on the Website and such changes shall automatically become effective immediately after they are posted on the Website. Unless otherwise stated, all fees shall be quoted in Indian Rupees. You shall be solely responsible for compliance of all applicable laws including those in India for making payments to Indianphotographyedition.
        </font></h3>

<br><br>
<h4 style=“color:grey”>Use of the Website</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
You agree, undertake and confirm that Your use of Website shall be strictly governed by the following binding principles:
1. You shall not host, display, upload, modify, publish, transmit, update or share any information which:<br>
(a) belongs to another person and to which You does not have any right to;<br>
(b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to "indecent representation of women" within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;<br>
(c) is misleading in any way;<br>
(d) is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, pedophiliac, racism, bigotry, hatred or physical harm of any kind against any group or individual;<br>
(e) Harasses or advocates harassment of another person;<br>
(f) Involves the transmission of "junk mail”, "chain letters”, or unsolicited mass mailing or "spamming";<br>
(g) promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;<br>
(h) infringes upon or violates any third party's rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity];<br>
(i) promotes an illegal or unauthorized copy of another person's copyrighted work (see "Copyright complaint" below for instructions on how to lodge a complaint about uploaded copyrighted material), such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing copyrighted photographs or links to copyrighted image files;<br>
(j) Contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);<br>
(k) Provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;<br>
(l) Provides instructional information via images / photographs or otherwise about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;<br>
(m) contains video, photographs, or images of another person (with a minor or an adult).<br>
(n) tries to gain unauthorized access or exceeds the scope of authorized access to the Website or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Website or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;<br>
(p) Solicits gambling or engages in any gambling activity which we, in our sole discretion, believe is or could be construed as being illegal;<br>
(q) Interferes with another USER's use and enjoyment of the Website or any other individual's User and enjoyment of similar services;<br>
(r) Refers to any website or URL that, in our sole discretion, contains material that is inappropriate for the Website or any other website, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.<br>
(s) Harm minors in any way;<br>
(t) infringes any patent, trademark, copyright or other proprietary rights or third party’s trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products;<br>
(u) violates any law for the time being in force;<br>
(v) Deceives or misleads the addressee/ users about the origin of images or photographs or any other product or any information which is grossly offensive or menacing in nature;<br>
(w) Impersonate another person;<br>
(x) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;<br>
(y) Threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.<br>
(z) Shall not be false, inaccurate or misleading;<br>
(aa) shall not, directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.<br>
(ab) shall not create liability for us or cause us to lose (in whole or in part) the services of Our internet service provider (“ISPs”) or other suppliers;<br>
2. You shall not use any “deep-link”, “page-scrape”, “robot”, “spider” or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Website or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Website. We reserve Our right to bar any such activity.<br>
3. You shall not attempt to gain unauthorized access to any portion or feature of the Website, or any other systems or networks connected to the Website or to any server, computer, network, or to any of the services offered on or through the Website, by hacking, password “mining” or any other illegitimate means.<br>
4. You shall not probe, scan or test the vulnerability of the Website or any network connected to the Website nor breach the security or authentication measures on the Website or any network connected to the Website. You may not reverse look-up, trace or seek to trace any information on any other User of or visitor to Website, or any other customer, including any account on the Website not owned by You, to its source, or exploit the Website or any service or information made available or offered by or through the Website, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than Your own information, as provided for by the Website.<br>
5. You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about Us or the brand name or domain name used by Us including the terms Indianphotographyedition, Indianphotographyedition.com, or otherwise engage in any conduct or action that might tarnish the image or reputation, of Indianphotographyedition or sellers on platform or otherwise tarnish or dilute any Indianphotographyedition’s trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by us. You agree that You will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Website or Indianphotographyedition’s systems or networks, or any systems or networks connected to Indianphotographyedition.<br>
6. You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Website or any transaction being conducted on the Website, or with any other person’s use of the Website.<br>
7. You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal You send to Us on or through the Website or any service offered on or through the Website. You may not pretend that You are, or that You represent, someone else, or impersonate any other individual or entity.<br>
 
8. You may not use the Website or any content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of Indianphotographyedition and / or others.<br>
 9. You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules there under as applicable and as amended from time to time and also all applicable Domestic laws, rules and regulations (including the provisions of any applicable Exchange Control Laws or Regulations in Force) and International Laws, Foreign Exchange Laws, Statutes, Ordinances and Regulations (including, but not limited to Sales Tax/VAT, Income Tax, Octroi, Service Tax, Central Excise, Custom Duty, Local Levies) regarding Your use of Our service and Your listing, purchase, solicitation of offers to purchase, and sale of products or services. You shall not engage in any transaction in an item or service, which is prohibited by the provisions of any applicable law including exchange control laws or regulations for the time being in force.<br>
10. Solely to enable Us to use the information You supply Us with, so that we are not violating any rights You might have in Your Information, You agree to grant Us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, rights or any other rights You have in Your Information, in any media now known or not currently known, with respect to Your Information. We will only use Your information in accordance with the Terms of Use and Privacy Policy applicable to use of the Website.<br>
11. From time to time, You shall be responsible for providing information relating to the products or services proposed to be sold by You. In this connection, You undertake that all such information shall be accurate in all respects. You shall not exaggerate or over emphasize the attributes of such products or services so as to mislead other Users in any manner.<br>
12. We reserve the right, but has no obligation, to monitor the materials posted on the Website. Indianphotographyedition shall have the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Use. Notwithstanding this right, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE WEBSITE AND IN YOUR PRIVATE MESSAGES. Please be advised that such Content posted does not necessarily reflect Indianphotographyedition’s views. In no event shall Indianphotographyedition assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on the Website. You hereby represent and warrant that You have all necessary rights in and to all Content which You provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libelous, tortious, or otherwise unlawful information.<br>
 
13. Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Website, including payment and delivery of related products or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between You and such advertiser. We shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on the Website.<br>
14. It is possible that other user (including unauthorized users or “hackers”) may post or transmit offensive or obscene materials on the Website and that You may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about You due to your use of the Website, and that the recipient may use such information to harass or injure You. We do not approve of such unauthorized uses, but by using the Website You acknowledge and agree that We are not responsible for the use of any personal information that You publicly disclose or share with others on the Website. Please carefully select the type of information that You publicly disclose or share with others on the Website.<br>
15. Indianphotographyedition shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your own or through group/s of people, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services).<br>

        </font></h3>

<br><br>
<h4 style=“color:grey”>Contents Posted on Site</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
All text, graphics, photographs, trademarks, logos, sounds, and artwork (collectively, “Content”), which are  third party / user generated content posted on the site, Indianphotographyedition has no control over such third party / user generated content as Indianphotographyedition is merely an intermediary for the purposes of this Terms of Use.
Except as expressly provided in these Terms of Use, no part of the Website and no Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including “mirroring”) to any other computer, server, Website or other medium for publication or distribution or for any commercial enterprise, without Indianphotographyedition’s express prior written consent.
You may use information on the products and services purposely made available on the Website for downloading, provided that You (1) do not remove any proprietary notice language in all copies of such documents, (2) use such information only for your personal, non-commercial informational purpose and do not copy or post such information on any networked computer or broadcast it in any media, (3) make no modifications to any such information, and (4) do not make any additional representations or warranties relating to such documents.
You shall be responsible for any notes, messages, emails, billboard postings, photos, drawings, profiles, opinions, ideas, images or other materials or information posted or transmitted to the Website (collectively, "Content"). Such Content will become Our property and You grant Us the worldwide, perpetual and transferable non exclusive rights in such Content. We shall be entitled to, consistent with Our Privacy Policy as adopted in accordance with applicable law, use the Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include the Content You provide. You agree that any Content You post may be used by us, consistent with Our Privacy Policy and Rules of Conduct on Site as mentioned herein, and You are not entitled to any payment or other compensation for such use.



        </font></h3>
<br><br>
<h4 style=“color:grey”>Privacy</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
We view protection of Your privacy as a very important principle. We understand clearly that You and Your Personal Information is one of Our most important assets. We store and process Your Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and Rules there under. Our current Privacy Policy is available at <a href="http://indianphotographyedition.com/index.php/welcome/privacy">http://indianphotographyedition.com/privacy</a>. If You object to Your Information being transferred or used in this way please do not use Website.
We and our affiliates will share / sell / transfer / license / covey some or all of your personal information with another business entity should we (or our assets) plan to merge with or are acquired by that business entity, or re-organization, amalgamation, restructuring of business or for any other reason whatsoever. Should such a transaction or situation occur, the other business entity or the new combined entity will be required to follow the privacy policy with respect to your personal information. Once you provide your information to us, you provide such information to us and our affiliate and we and our affiliate may use such information to provide you various services with respect to your transaction whether such transaction are conducted on <a href="http://www.indianphotographyedition.com">www.Indianphotographyedition.com</a> or with third party merchant's or third party merchant's website.
  </font></h3>

<br><br>
<h4 style=“color:grey”>Disclaimer of Warranties and Liability</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
This Website, all the materials and products (including but not limited to software) and services, included on or otherwise made available to You through this site are provided on “as is” and “as available” basis without any representation or warranties, express or implied except otherwise specified in writing. Without prejudice to the forgoing paragraph, Indianphotographyedition does not warrant that:
• This Website will be constantly available, or available at all; or
• The information on this Website is complete, true, accurate or non-misleading.

Indianphotographyedition will not be liable to You in any way or in relation to the Contents of, or use of, or otherwise in connection with, the Website. Indianphotographyedition does not warrant that this site; information, Content, materials, product (including software) or services included on or otherwise made available to You through the Website; their servers; or electronic communication sent from Us are free of viruses or other harmful components.
Nothing on Website constitutes, or is meant to constitute, advice of any kind. All the Products sold on Website are governed by different state laws and if Seller is unable to deliver such Products due to implications of different state laws, Seller will return or will give credit for the amount (if any) received in advance by Seller from the sale of such Product that could not be delivered to You. 
You will be required to enter a valid phone number while placing an order on the Website. By registering Your phone number with us, You consent to be contacted by Us via phone calls and/or SMS notifications, in case of any order or shipment or delivery related updates. We will not use your personal information to initiate any promotional phone calls or SMS.
        </font></h3>

<br><br>
<h4 style=“color:grey”>Selling</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
As a registered seller, you are allowed to list item(s) for sale on the Website in accordance with the Policies which are incorporated by way of reference in this Terms of Use. You must be legally able to sell the item(s) you list for sale on our Website. You must ensure that the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties. Listings may only include text descriptions, graphics and pictures that describe your item for sale. All listed items must be listed in an appropriate category on the Website. All listed items must be kept in stock for successful fulfilment of sales.

The listing description of the item must not be misleading and must describe actual condition of the product. If the item description does not match the actual condition of the item, you agree to refund any amounts that you may have received from the Buyer. You agree not to list a single product in multiple quantities across various categories on the Website. Indianphotographyedition reserves the right to delete such multiple listings of the same product listed by you in various categories.

        </font></h3>

<br><br><h4 style=“color:grey”>Services</h4><br><br><br>
<h4 style=“color:grey”>Payment</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
While availing any of the payment method/s available on the Website, we will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to:
 Lack of authorization for any transaction/s, or
1.	Exceeding the preset limit mutually agreed by You and between "Bank/s", or
2.	Any payment issues arising out of the transaction, or
3.	Decline of transaction for any other reason/s
 All payments made against the purchases/services on Website by you shall be directly made to the seller in a form (cash on delivery / wire transfer / Cheque) and currency suitable to the seller. Website will not facilitate transaction in whatsoever manner. The website is not responsible for any transaction and payments made therein or warranties and Guarantees of the product.   
Before shipping / delivering your order to you, Seller may request you to provide supporting documents (including but not limited to Govt. issued ID and address proof) to establish the ownership of the payment instrument used by you for your purchase. This is done in the interest of providing a safe online shopping environment to Our Users.
Further:
Transactions, Transaction Price and all commercial terms such as Delivery, Dispatch of products and/or services are as per principal to principal bipartite contractual obligations between Buyer and Seller. The Website is merely a platform which provides an interface to display products related to photography for sale. The Web site shall not render liable or responsible for the non–delivery, non-receipt, non-payment, damage, breach of representations and warranties, non-provision of after sales or warranty services or fraud as regards the products and /or services listed on Indianphotographyedition’s Website.


        </font></h3>

<br><br>
<h4 style=“color:grey”>Payment Facility for Buyers:</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
• You, as a Buyer, understand that upon initiating a Transaction You are entering into a legally binding and enforceable contract with the Seller to purchase the products and /or services from the Seller using the Payment Facility, and You shall pay the Transaction Price through Your Issuing Bank to the Seller using Payment Facility suitable to the seller directly. The Indianphotographyedition should not be in any way responsible for any transaction and the transaction should be purely a bi-partie transaction.

        </font></h3>

<br><br>
<h4 style=“color:grey”>Compliance with Laws:</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
Buyer and Seller shall comply with all the applicable laws (including without limitation Foreign Exchange Management Act, 1999 and the rules made and notifications issued there under and the Exchange Control Manual as may be issued by Reserve Bank of India from time to time, Customs Act, Information and Technology Act, 2000 as amended by the Information Technology (Amendment) Act 2008, Prevention of Money Laundering Act, 2002 and the rules made there under, Foreign Contribution Regulation Act, 1976 and the rules made there under, Income Tax Act, 1961 and the rules made there under, Export Import Policy of government of India) applicable to them respectively for doing transaction using Indianphotographyedition Website.

        </font></h3>

<br><br>
<h4 style=“color:grey”>DRM Specifications:</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
The DRM (Digital Rights Management) enables us to restrict certain permissions. The DRM specifications restrict the following permissions:<br><br><br>

<table class="table">
<tr>
<th>Default Restrictions</th><th>Indianphotographyedition Settings</th>
</tr>
<tr><td>Printing</td><td>Not Allowed</td></tr>
<tr><td>Copying</td><td>Not Allowed</td></tr>
<tr><td>Side-Loading</td><td>Not Allowed</td></tr>
<tr><td>E-Mailing</td><td>Not Allowed</td></tr>
<tr><td>Saving Images</td><td>Not Allowed</td></tr>
<tr><td>Read out aloud</td><td>Not Allowed</td></tr>
<tr><td>Number of distinct devices for file downloading</td><td>Allowed</td></tr>
<tr><td>Social media sharing</td><td>140 words</td></tr></table>


        </font></h3>

<br><br>
<h4 style=“color:grey”>Indemnity</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
You shall indemnify and hold harmless Indianphotographyedition, its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.

        </font></h3>

<br><br>
<h4 style=“color:grey”>Applicable Law</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
Terms of Use shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be exclusively in Mumbai.

        </font></h3>

<br><br>
<h4 style=“color:grey”>Jurisdictional Issues/Sale in India Only</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
Unless otherwise specified, the material on the Website is presented solely for the purpose of sale in India. Indianphotographyedition make no representation that materials in the Website are appropriate or available for use in other locations/Countries other than India. Those who choose to access this site from other locations/Countries other than India do so on their own initiative and Indianphotographyedition is not responsible for supply of products/refund for the products ordered from other locations/Countries.

        </font></h3>

<br><br>
<h4 style=“color:grey”>Trademark, Copyright and Restriction</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
This site is controlled and operated by Indianphotographyedition and products are sold by respective Sellers. All material on this site, including images, illustrations are protected by copyrights, trademarks, and other intellectual property rights. Material on Website is solely for your personal, non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by email or other electronic means and whether directly or indirectly and You must not assist any other person to do so. Without the prior written consent of the owner, modification of the materials, use of the materials on any other website or networked computer environment or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is prohibited. Any use for which You receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause.

        </font></h3>

<br><br>
<h4 style=“color:grey”>Copyrights complaint</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
Indianphotographyedition respects the intellectual property of others. In case you feel that your copyrights have been infringed, you can write to Indianphotographyedition at _______________@ Indianphotographyedition.com.

        </font></h3>

<br><br>
<h4 style=“color:grey”>Product Description</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
Indianphotographyedition we do not warrant that Product description or other content of this Website is accurate, complete, reliable, current, or error-free and assumes no liability in this regard.
        </font></h3>

<br><br>
<h4 style=“color:grey”>Limitation of Liability</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
IN NO EVENT SHALL INDIANPHOTOGRAPHYEDITION BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THESE TERMS OF USE, EVEN IF USER HAS BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.
        </font></h3>

<br><br>
<h4 style=“color:grey”>Contact Us</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
Please send any questions or comments (including all inquiries unrelated to copyright infringement) regarding this Website to <a href="#">contactus@ indianphotographyedition.com.</a>

        </font></h3>

<br><br>
<h4 style=“color:grey”>Grievance officer</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
In accordance with Information Technology Act 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below:
Mr. Palash Gandhi
Phone: +91- 
Email: grievances @ indianphotographyedition.com
Time: Mon – Sat (9:00 – 18:00)


        </font></h3>

<br><br>
<h4 style=“color:grey”>POLICIES</h4><br><br><br><h4 style=“color:grey”>Profanity Policy</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
Indianphotographyedition prohibits the use of language that is racist, hateful, sexual or obscene in nature in a public area.
This policy extends to text within listings, on Seller pages and all other areas of the site that another User may view. If the profane words are part of a title for the item being sold, we allow Sellers to 'blur' out the bulk of the offending word with asterisks (i.e., s*** or f***).
Please report any violations of this policy to the correct area for review:
•	Report offensive Display Names
•	Report offensive language in a listing or otherwise
If a feedback comment; or any communication made between Users on the Website; or email communication between Users in relation to transactions conducted on Website contain profanity, please review Our feedback removal policy and submit a request for action/removal.
Disciplinary action may result in the indefinite suspension of a User's account, temporary suspension, or a formal warning.
Indianphotographyedition will consider the circumstances of an alleged policy violation and the user's trading records before taking action.
Violations of this policy may result in a range of actions, including:
1.	Limits placed on account privileges;
2.	Loss of special status;
3.	Account suspension.


        </font></h3>

<br><br>
<h4 style=“color:grey”>Buyer Protection Program</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
<i>In case of a dispute where the Seller is unable to provide a refund or a replacement, Indianphotographyedition will actively try to work towards reaching a resolution though it’s legally not bound for the same.
The Buyer Protection Program covers Buyers who are unable to successfully resolve their dispute with the Seller or are not satisfied the resolution provided by the Seller.
The Buyer can write to Indianphotographyedition.com if the issue with the Seller is not resolved. Indianphotographyedition’s  Customer Support team will look into the case to check for possible fraud and if the Buyer has been blacklisted/blocked from making purchases on the Website. Only after verifying these facts, a dispute can be registered.
In due course of resolution, Indianphotographyedition’s Customer Support Team will facilitate a conference call including the Seller and the Buyer.
When a dispute has been raised, Indianphotographyedition may provide both the parties access to each others Display Names, contact details including email addresses and other details pertaining to the dispute. Buyers and Sellers are subject to final consent from Indianphotographyedition for settling the dispute.
Buyer Eligibility and Restrictions
● Only the Buyers who have purchased the product on Indianphotographyedition are eligible for the Buyer Protection Program.
● Buyers can file a dispute within 45 days from the date of delivery of the product
● Any damage or loss to the product after delivery will not be covered under this program and will completely be the Buyer’s responsibility. Buyers should refuse to accept delivery if the item is damaged.
● To be able to take advantage of the Buyer Protection Program, Buyers should first contact the Seller and attempt to resolve the issue. If the Buyer doesn't hear from the Seller or is unable to resolve the issue with the Seller even after contact, a dispute can be raised with Indianphotographyedition by writing an email to Indianphotographyedition.com
● Fraudulent charges and claims are not covered under Buyer Protection Program
● Blacklisted and Blocked Buyers are not covered by the Buyer Protection Program.
● Buyers who have reached their maximum lifetime limit for claims are also not eligible. Buyers can make a maximum of 5 claims per year on Indianphotographyedition. If the claim was withdrawn, it is not counted. The coverage amount will be limited to ₹50,000
● Through the Buyer Protection program, Indianphotographyedition does not provide any guarantee/warranty to Buyers for products sold on Indianphotographyedition against technical/manufacturing defects.
● Raising disputes against Sellers does not automatically entitle the Buyer to a refund or replacement for the product purchased. Indianphotographyedition shall verify the disputes so raised and may process only such claims that are valid and genuine.
● Indianphotographyedition shall at no point be responsible for any direct or indirect losses, expenses, costs of any nature whatsoever that may be incurred by any Buyer/Seller.
● Indianphotographyedition reserves its right to initiate civil and/or criminal proceedings against a User who, files an invalid and/or false claims or provides false, incomplete, or misleading information. In addition to the legal proceedings as aforesaid, Indianphotographyedition may at its sole discretion suspend, block, restrict, cancel the Display Name [and its related Display Names] of such User and/or disqualify that user and any related users from availing protection through this program.
● Decisions made by Indianphotographyedition under the Buyer Protection Program shall be final and binding on its Users.
● Indianphotographyedition reserves the right to modify / discontinue Buyer Protection Program without any prior notice period to its Users.</i>


        </font></h3>

<br><br>
<h4 style=“color:grey”>Email Abuse & Threat Policy</h4>


    <h3 style="font-size:1.3em;color:#CCC;line-height:150%;text-align:justify"> <font face="Calibri">
Private communication, including email correspondence, is not regulated by Indianphotographyedition. Indianphotographyedition encourages its Users to be professional, courteous and respectful when communicating by email.
However, Indianphotographyedition will investigate and can take action on certain types of unwanted emails that violate Indianphotographyedition policies.
Such instances:
Threats of Bodily Harm – Indianphotographyedition does not permit Users to send explicit threats of bodily harm.
Misuse of Indianphotographyedition System – Indianphotographyedition allows Users to facilitate transactions through the Indianphotographyedition system, but will investigate any misuse of this service.
Spoof (Fake) email – Indianphotographyedition will never ask you to provide sensitive information through email. In case you receive any spoof (fake) email, you are requested to report the same to Us through ‘Contact Us’ tab.
Spam (Unsolicited Commercial email) – Indianphotographyedition’s spam policy applies only to unsolicited commercial messages sent by Indianphotographyedition Users. Indianphotographyedition Users are not allowed to send spam messages to other Users.
Offers to Buy or Sell Outside of Indianphotographyedition – Indianphotographyedition prohibits email offers to buy or sell listed products outside of the Indianphotographyedition Website. Offers of this nature are a potential fraud risk for both Buyers and Sellers.
Indianphotographyedition policy prohibits user-to-user threats of physical harm via any method including, phone, email and on Our public message boards.
Violations of this policy may result in a range of actions, including:
•	Limits on account privileges
•	Account suspension
•	Cancellation of listings
•	Loss of special status
Other Businesses
Indianphotographyedition does not take responsibility or liability for the actions, products, content and services on the Website, which are linked to Affiliates and / or third party websites using Website’s APIs or otherwise. In addition, the Website may provide links to the third party websites of Our affiliated companies and certain other businesses for which, Indianphotographyedition assumes no responsibility for examining or evaluating the products and services offered by them. Indianphotographyedition do not warrant the offerings of, any of these businesses or individuals or the content of such third party website(s). Indianphotographyedition does not endorse, in any way, any third party website(s) or content thereof.


        </font></h3></div><br><br><br><br>
        <table style="border:none;background-color:transparent">
        <tr><td><form action='<?php echo base_url()?>index.php/login/register' method="post"> 
	<input type="hidden" value="agree" name="tnc">
	<input type="submit" value="I agree" style="width:200px;align:center;" class="push socle">
	</form></td><td>
        <form action='<?php echo base_url()?>' method="post"> 
	<input type="submit" value="I disagree" style="width:200px;align:center;" class="push socle">
	</form></td></tr></table>
    <br><br>
</div>